config/routes.rb
Commenting::Application.routes.draw do
  resources :users

  resources :comment_threads

  resources :comments

  match ':controller(/:action(/:id(.:format)))'
end

app/models/comment_thread.rb
class CommentThread < ActiveRecord::Base

  validates :title, :presence => true
  validates :user_id, :presence => true, :numericality => true
  validates :body, :presence => true

  has_many :comments, :order => 'created_at'
  belongs_to :user

end

app/controllers/comment_threads_controller.rb
class CommentThreadsController < ApplicationController
  # GET /comment_threads
  # GET /comment_threads.xml
  def index
    sort = case params[:sort]
             when "title" then
               "title"
             when "owner" then
               "user_id"
             when "created_at" then
               "created_at"
             when "comments_count" then
               "comments_count"
             when "title_reverse" then
               "title DESC"
             when "owner_reverse" then
               "user_id DESC"
             when "created_at_reverse" then
               "created_at DESC"
             when "comments_count_reverse" then
               "comments_count DESC"
           end

#    if sort.starts_with? 'number_of_comments'
#      @comment_threads = CommentThread.all().sort_by { |t| -t.comments.size }
#
#      if sort.ends_with? 'DESC'
#        @comment_threads = @comment_threads.reverse
#      end
#
##      @comment_threads = CommentThread.all(:select => "#{CommentThread.table_name}.*, COUNT(#{Comment.table_name}.id) number_of_comments",
##                                           :joins => :comments,
##                                           :order => "number_of_comments DESC")
#
#    else
      @comment_threads = CommentThread.order(sort)
#    end


    respond_to do |format|
      format.html # index.html.erb
      format.xml { render :xml => @comment_threads }
    end
  end

  # GET /comment_threads/1
  # GET /comment_threads/1.xml
  def show
    @comment_thread = CommentThread.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml { render :xml => @comment_thread }
    end
  end

  # GET /comment_threads/new
  # GET /comment_threads/new.xml
  def new
    @comment_thread = CommentThread.new
    @comment_thread.user_id = 1

    respond_to do |format|
      format.html # new.html.erb
      format.xml { render :xml => @comment_thread }
    end
  end

  # GET /comment_threads/1/edit
  def edit
    @comment_thread = CommentThread.find(params[:id])
  end

  # POST /comment_threads
  # POST /comment_threads.xml
  def create
    @comment_thread = CommentThread.new(params[:comment_thread])

    respond_to do |format|
      if @comment_thread.save
        format.html { redirect_to(@comment_thread, :notice => 'Comment thread was successfully created.') }
        format.xml { render :xml => @comment_thread, :status => :created, :location => @comment_thread }
      else
        format.html { render :action => "new" }
        format.xml { render :xml => @comment_thread.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /comment_threads/1
  # PUT /comment_threads/1.xml
  def update
    @comment_thread = CommentThread.find(params[:id])

    respond_to do |format|
      if @comment_thread.update_attributes(params[:comment_thread])
        format.html { redirect_to(@comment_thread, :notice => 'Comment thread was successfully updated.') }
        format.xml { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml { render :xml => @comment_thread.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /comment_threads/1
  # DELETE /comment_threads/1.xml
  def destroy
    @comment_thread = CommentThread.find(params[:id])
    @comment_thread.destroy

    respond_to do |format|
      format.html { redirect_to(comment_threads_url) }
      format.xml { head :ok }
    end
  end

  def new_comment
    @comment = Comment.new
    @comment.user_id = 1
    @comment.comment_thread_id = params[:id]

    respond_to do |format|
      format.html # new.html.erb
      format.xml { render :xml => @comment }
    end
  end

  def create_comment
    @comment = Comment.new(params[:comment])
    @comment.user_id = 1
    @comment_thread = CommentThread.find(@comment.comment_thread_id)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to(@comment_thread) }
        format.xml { render :xml => @comment, :status => :created, :location => @comment }
      else
        format.html { render :action => "new" }
        format.xml { render :xml => @comment.errors, :status => :unprocessable_entity }
      end
    end
  end

end

app/helpers/comment_threads_helper.rb
module CommentThreadsHelper

  def sort_td_class_helper(sort)
    result = 'class=\'sortup\'' if params[:sort] == sort
    result = 'class=\'sortdown\'' if params[:sort] == sort + "_reverse"
    return result
  end

  def sort_link_helper(text, sort)
    sort += "_reverse" if params[:sort] == sort
    options = {
        :action => 'index',
        :sort => sort,
    }
    html_options = {
        :title => "Sort by this field",
    }
    link_to text, options, html_options
  end

   def sort_td_image_helper(param)
    result = image_tag '/images/arrow_up_blue.png' if params[:sort] == param
    result = image_tag '/images/arrow_down_blue.png' if params[:sort] == param + "_reverse"
    return result
   end

end

app/views/comment_threads/_form.html.erb
<%= form_for(@comment_thread) do |f| %>
    <% if @comment_thread.errors.any? %>
        <div id="error_explanation">
            <h2><%= pluralize(@comment_thread.errors.count, "error") %> prohibited this comment_thread from being
                saved:</h2>

            <ul>
                <% @comment_thread.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <div class="field">
        <%= f.label :title %><br/>
        <%= f.text_field :title %>
    </div>
    <div class="field">
        <%= f.label :body %><br/>
        <%= f.text_area :body %>
    </div>
    <div class="hidden">
        <%= f.hidden_field :user_id %>
    </div>
    <div class="actions">
        <%= f.submit submit_text %>
    </div>
<% end %>

app/views/comment_threads/_nav.html.erb
<div id="header">
    <!--a href="http://www.helium.com"><img src="/images/helium_logo.gif"/></a> -->
    <div id="nav">
        <ul>
            <li><%= link_to 'Threads', comment_threads_path %></li>
            <% if @comment_thread.nil? %>
                <li><%= link_to "New Thread", new_comment_thread_path %></li>
            <% else %>
                <li><%= link_to 'Edit Thread', edit_comment_thread_path(@comment_thread) %></li>
            <% end %>
            <li><%= link_to 'Users', users_path %></li>
        </ul>
    </div>
</div>

app/views/comment_threads/edit.html.erb
<h1>Update Thread</h1>

<%= render :partial => 'form', :locals => {:submit_text => 'Update'} %>

app/views/comment_threads/index.html.erb
<%= render 'nav' %>

<h1>Threads</h1>

<table>
    <tr>
        <th <%= sort_td_class_helper "title" %>>
            <%= sort_link_helper "Title", "title" %>
        </th>
        <th <%= sort_td_class_helper "owner" %>>
            <%= sort_link_helper "Owner", "owner" %>
        </th>
        <th <%= sort_td_class_helper "created_at" %>>
            <%= sort_link_helper "Date Created", "created_at" %>
        </th>
        <th <%= sort_td_class_helper "comments_count" %>>
            <%= sort_link_helper "Activity", "comments_count" %>
        </th>
        <th></th>
    </tr>

    <% @comment_threads.each do |comment_thread| %>
        <tr>
            <td><%= link_to comment_thread.title, comment_thread %></td>
            <td><%= link_to "#{comment_thread.user.first_name} #{comment_thread.user.last_name}", comment_thread.user %></td>
            <td><%= comment_thread.created_at.to_s(:long) %></td>
            <td><%= pluralize(comment_thread.comments_count, 'comment')%>
            </td>
            <td class="links">
                <%= link_to image_tag("/images/Edit-icon_small.png", :border=>0, :alt => "Edit"), edit_comment_thread_path(comment_thread) %>
                <%= link_to image_tag("/images/Delete-icon_small.png", :border=>0, :alt => "Delete"), comment_thread, :confirm => 'Are you sure?', :method => :delete %>
            </td>
        </tr>
    <% end %>
</table>

app/views/comment_threads/new.html.erb
<h1>New Thread</h1>

<%= render :partial => 'form', :locals => {:submit_text => 'Create'} %>

app/views/comment_threads/show.html.erb
<script type="text/javascript" src="http://www.google.com/jsapi"></script>
<script type="text/javascript">

    // Load the latest 1.* version of JQuery
    google.load("jquery", "1");

    google.setOnLoadCallback(function() {

        // reply show/hide
        $("*[class^=reply_button_for_]").click(function(event) {
            var button = $(this).attr('class');
            var id = button.split('_').last();

            $("#reply_for_" + id).toggle();
        });

    });

</script>

<%= render 'nav' %>

<p id="notice"><%= notice %></p>

<div class="thread">
    <div class="user">
        <div class="image">
            <% if @comment_thread.user.image.nil? %>
                <img src="<%= "/images/User-icon_large.png" %>" height="60" width="60">
            <% else %>
                <img src="<%= "/images/#{@comment_thread.user.image}" %>" height="60" width="60">
            <% end %>
        </div>
    </div>
    <div class="info">
        <div class="title">
            <%= @comment_thread.title %>
        </div>
        <div class="name">
            <%= "By #{@comment_thread.user.first_name} #{@comment_thread.user.last_name}" %>
        </div>
        <div class="body">
            <%= @comment_thread.body %>
        </div>
    </div>
</div>
<div class="comments">
    <% if @comment_thread.comments_count > 0 %>
        <h2><%= pluralize(@comment_thread.comments_count, "comment") %></h2>
    <% end %>
    <% @comment_thread.comments.each do |comment| %>
        <%= render comment %>
    <% end %>
    <div class="newComment">
        <%= form_for(@comment_thread.comments.new) do |f| %>
            <div class="field">
                <%= f.hidden_field :comment_thread_id %>
            </div>
            <div class="field">
                <% if @comment_thread.comments_count > 0 %>
                    <%= f.label 'Post your comment' %><br/>
                <% else %>
                    <%= f.label 'Be the first to comment' %><br/>
                <% end %>
                <%= f.text_area :body %>
            </div>
            <div class="actions">
                <%= f.submit 'Post' %>
            </div>
        <% end %>
    </div>
</div>